name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # once a day
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: Hardikrepo
          template: github_dark
